#!/usr/bin/env python3
"""Generate Cpp_Dedicated_5D_Unfold/generated/Dedicated_5D_Binning.h from the live Python maps.

C++ only needs the dense-5D Convert_All_Kinematic_Bins lookups, skip_condition_z_pT_bins,
and Get_Num_of_z_pT_Bins_w_Migrations. The huge baked 3D dictionaries in
Convert_MultiDim_Kinematic_Bins.py are not copied.
"""

import argparse
import os
import sys
from datetime import datetime

_BOOT = os.path.abspath(os.path.dirname(__file__))
if(_BOOT not in sys.path):
    sys.path.insert(0, _BOOT)

DEFAULT_OUT = os.path.join(_BOOT, "Cpp_Dedicated_5D_Unfold", "generated", "Dedicated_5D_Binning.h")


def load_python_maps():
    from MyCommonAnalysisFunction_richcap import skip_condition_z_pT_bins, Get_Num_of_z_pT_Bins_w_Migrations
    from Convert_MultiDim_Kinematic_Bins import create_dense_5d_bin_mapping, Convert_All_Kinematic_Bins
    return skip_condition_z_pT_bins, Get_Num_of_z_pT_Bins_w_Migrations, create_dense_5d_bin_mapping, Convert_All_Kinematic_Bins


def format_int_row(values, indent="    "):
    return indent + ", ".join(str(int(v)) for v in values)


def write_header(out_path):
    skip_condition_z_pT_bins, Get_Num_of_z_pT_Bins_w_Migrations, create_dense_5d_bin_mapping, Convert_All_Kinematic_Bins = load_python_maps()
    mapping = create_dense_5d_bin_mapping()
    convert_dict = mapping["Convert_MultiDim_Kinematic_Bins_dense_5D"]
    total_hist_bins = int(mapping["total_hist_bins"])

    max_q2y = 17
    max_zpt = 40
    totals = [0] * (max_q2y + 1)
    lasts = [0] * (max_q2y + 1)
    skip_table = [[0 for _ in range(max_zpt + 1)] for _ in range(max_q2y + 1)]
    start_slot = [[0 for _ in range(max_zpt + 1)] for _ in range(max_q2y + 1)]

    for q2y in range(1, max_q2y + 1):
        total, last, _migration = Get_Num_of_z_pT_Bins_w_Migrations(Q2_y_Bin_Num_In=q2y)
        totals[q2y] = int(total)
        lasts[q2y] = int(last)
        for zpt in range(0, max_zpt + 1):
            skip_table[q2y][zpt] = 1 if(skip_condition_z_pT_bins(q2y, zpt, BINNING_METHOD="Y_bin")) else 0

    for key, value in convert_dict.items():
        if(key.endswith(" -> MultiDim_Q2_y_z_pT_phi_h") and key.startswith("Q2-y=")):
            left = key.split(" -> ", 1)[0]
            q_part, z_part = left.split(", ")
            q2y = int(q_part.split("=")[1])
            zpt = int(z_part.split("=")[1])
            start_slot[q2y][zpt] = int(value)

    reverse_q2y = [0] * (total_hist_bins + 1)
    reverse_zpt = [0] * (total_hist_bins + 1)
    has_reverse = [0] * (total_hist_bins + 1)
    for key, value in convert_dict.items():
        if(key.startswith("MultiDim_Q2_y_z_pT_phi_h=") and key.endswith(" -> Q2-y")):
            slot = int(key.split("=")[1].split(" ")[0])
            reverse_q2y[slot] = int(value)
            has_reverse[slot] = 1
        elif(key.startswith("MultiDim_Q2_y_z_pT_phi_h=") and key.endswith(" -> z-pT")):
            slot = int(key.split("=")[1].split(" ")[0])
            reverse_zpt[slot] = int(value)
            has_reverse[slot] = 1

    lines = []
    a = lines.append
    a("// Auto-generated by Generate_Dedicated_5D_Unfold_Cpp_Binning.py")
    a(f"// Generated: {datetime.now().isoformat(timespec='seconds')}")
    a("// Do not hand-edit. Source of truth: skip_condition_z_pT_bins, Get_Num_of_z_pT_Bins_w_Migrations,")
    a("// and Convert_MultiDim_Kinematic_Bins.create_dense_5d_bin_mapping (live map, not baked snapshot).")
    a("#pragma once")
    a("")
    a("#include <cstdio>")
    a("#include <string>")
    a("#include <tuple>")
    a("#include <vector>")
    a("")
    a("namespace sidis5d {")
    a("")
    a("struct ConvertResult {")
    a("    bool ok = false;")
    a("    int value = 0;")
    a("    bool operator==(const ConvertResult& other) const {")
    a("        if((!ok) && (!other.ok)){ return true; }")
    a("        if((ok) && (other.ok)){ return value == other.value; }")
    a("        return false;")
    a("    }")
    a("    bool operator!=(const ConvertResult& other) const { return !(*this == other); }")
    a("};")
    a("")
    a(f"const int kMaxQ2y = {max_q2y};")
    a(f"const int kMaxZpT = {max_zpt};")
    a(f"const int kTotalHistBins = {total_hist_bins};")
    a("")
    a("const int kZptTotal[18] = {")
    a(format_int_row(totals) + ",")
    a("};")
    a("const int kZptLast[18] = {")
    a(format_int_row(lasts) + ",")
    a("};")
    a("")
    a("const int kSkipZpT[18][41] = {")
    for q2y in range(0, max_q2y + 1):
        a("    {" + ", ".join(str(int(v)) for v in skip_table[q2y]) + "},")
    a("};")
    a("")
    a("const int kStartSlot[18][41] = {")
    for q2y in range(0, max_q2y + 1):
        a("    {" + ", ".join(str(int(v)) for v in start_slot[q2y]) + "},")
    a("};")
    a("")
    a(f"const int kHasReverseSlot[{total_hist_bins + 1}] = {{")
    # wrap long arrays
    row = []
    for i, v in enumerate(has_reverse):
        row.append(str(int(v)))
        if(len(row) == 24):
            a("    " + ", ".join(row) + ",")
            row = []
    if(row):
        a("    " + ", ".join(row) + ",")
    a("};")
    a(f"const int kReverseQ2y[{total_hist_bins + 1}] = {{")
    row = []
    for v in reverse_q2y:
        row.append(str(int(v)))
        if(len(row) == 24):
            a("    " + ", ".join(row) + ",")
            row = []
    if(row):
        a("    " + ", ".join(row) + ",")
    a("};")
    a(f"const int kReverseZpT[{total_hist_bins + 1}] = {{")
    row = []
    for v in reverse_zpt:
        row.append(str(int(v)))
        if(len(row) == 24):
            a("    " + ", ".join(row) + ",")
            row = []
    if(row):
        a("    " + ", ".join(row) + ",")
    a("};")
    a("")
    a("inline std::tuple<int, int, std::vector<int> > Get_Num_of_z_pT_Bins_w_Migrations(int Q2_y_Bin_Num_In){")
    a("    if((Q2_y_Bin_Num_In < 1) || (Q2_y_Bin_Num_In > kMaxQ2y)){")
    a("        std::vector<int> migration;")
    a("        for(int i = 1; i < 55; ++i){ migration.push_back(i); }")
    a("        return std::make_tuple(1, 1, migration);")
    a("    }")
    a("    const int total = kZptTotal[Q2_y_Bin_Num_In];")
    a("    const int last = kZptLast[Q2_y_Bin_Num_In];")
    a("    std::vector<int> migration;")
    a("    // Return [2] is unused by Dedicated_5D_Unfold (skip_condition is table-driven).")
    a("    return std::make_tuple(total, last, migration);")
    a("}")
    a("")
    a("inline bool skip_condition_z_pT_bins(int Q2_Y_BIN, int Z_PT_BIN){")
    a("    if((Q2_Y_BIN < 1) || (Q2_Y_BIN > kMaxQ2y) || (Z_PT_BIN < 0) || (Z_PT_BIN > kMaxZpT)){")
    a("        return false;")
    a("    }")
    a("    return kSkipZpT[Q2_Y_BIN][Z_PT_BIN] != 0;")
    a("}")
    a("")
    a("inline ConvertResult Convert_All_Kinematic_Bins(const std::string& Start_Bins_Name, const std::string& End_Bins_Name){")
    a("    std::string check = Start_Bins_Name + \" -> \" + End_Bins_Name;")
    a("    auto replace_all = [](std::string& s, const std::string& from, const std::string& to){")
    a("        size_t pos = 0;")
    a("        while((pos = s.find(from, pos)) != std::string::npos){")
    a("            s.replace(pos, from.size(), to);")
    a("            pos += to.size();")
    a("        }")
    a("    };")
    a("    replace_all(check, \"3D_Bins\", \"MultiDim_z_pT_phi_h\");")
    a("    replace_all(check, \"5D_Bins\", \"MultiDim_Q2_y_z_pT_phi_h\");")
    a("    ConvertResult result;")
    a("    const std::string arrow = \" -> \";")
    a("    const size_t split = check.find(arrow);")
    a("    if(split == std::string::npos){ return result; }")
    a("    const std::string left = check.substr(0, split);")
    a("    const std::string right = check.substr(split + arrow.size());")
    a("    if(right == \"MultiDim_Q2_y_z_pT_phi_h\"){")
    a("        // \"Q2-y=Q, z-pT=Z\"")
    a("        int q2y = 0;")
    a("        int zpt = 0;")
    a("        if(std::sscanf(left.c_str(), \"Q2-y=%d, z-pT=%d\", &q2y, &zpt) == 2){")
    a("            if((q2y >= 1) && (q2y <= kMaxQ2y) && (zpt >= 0) && (zpt <= kMaxZpT) && (kStartSlot[q2y][zpt] > 0)){")
    a("                result.ok = true;")
    a("                result.value = kStartSlot[q2y][zpt];")
    a("            }")
    a("        }")
    a("        return result;")
    a("    }")
    a("    if((right == \"Q2-y\") || (right == \"z-pT\")){")
    a("        int slot = 0;")
    a("        if(std::sscanf(left.c_str(), \"MultiDim_Q2_y_z_pT_phi_h=%d\", &slot) == 1){")
    a("            if((slot >= 0) && (slot <= kTotalHistBins) && (kHasReverseSlot[slot] != 0)){")
    a("                result.ok = true;")
    a("                result.value = (right == \"Q2-y\") ? kReverseQ2y[slot] : kReverseZpT[slot];")
    a("            }")
    a("        }")
    a("        return result;")
    a("    }")
    a("    return result;")
    a("}")
    a("")
    a("} // namespace sidis5d")
    a("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return {
        "out_path": out_path,
        "n_convert": len(convert_dict),
        "total_hist_bins": total_hist_bins,
        "Convert_All_Kinematic_Bins": Convert_All_Kinematic_Bins,
        "skip_condition_z_pT_bins": skip_condition_z_pT_bins,
        "Get_Num_of_z_pT_Bins_w_Migrations": Get_Num_of_z_pT_Bins_w_Migrations,
        "start_slot": start_slot,
        "has_reverse": has_reverse,
        "reverse_q2y": reverse_q2y,
        "reverse_zpt": reverse_zpt,
        "skip_table": skip_table,
        "lasts": lasts,
    }


def self_check(info):
    Convert_All_Kinematic_Bins = info["Convert_All_Kinematic_Bins"]
    skip_condition_z_pT_bins = info["skip_condition_z_pT_bins"]
    Get_Num_of_z_pT_Bins_w_Migrations = info["Get_Num_of_z_pT_Bins_w_Migrations"]
    failures = []

    def conv_cpp(start, end):
        if(end == "MultiDim_Q2_y_z_pT_phi_h"):
            left = start
            if(not left.startswith("Q2-y=")):
                return None
            q_part, z_part = left.split(", ")
            q2y = int(q_part.split("=")[1])
            zpt = int(z_part.split("=")[1])
            val = info["start_slot"][q2y][zpt]
            return val if(val > 0) else None
        if(end in ["Q2-y", "z-pT"]):
            slot = int(start.split("=")[1])
            if((slot < 0) or (slot >= len(info["has_reverse"])) or (info["has_reverse"][slot] == 0)):
                return None
            return info["reverse_q2y"][slot] if(end == "Q2-y") else info["reverse_zpt"][slot]
        return None

    for q2y in range(1, 18):
        py_last = Get_Num_of_z_pT_Bins_w_Migrations(Q2_y_Bin_Num_In=q2y)[1]
        if(int(py_last) != int(info["lasts"][q2y])):
            failures.append(f"last mismatch Q2-y={q2y}: python={py_last} table={info['lasts'][q2y]}")
        z_max = int(py_last)
        for zpt in range(0, z_max + 1):
            py_skip = bool(skip_condition_z_pT_bins(q2y, zpt, BINNING_METHOD="Y_bin"))
            cpp_skip = bool(info["skip_table"][q2y][zpt])
            if(py_skip != cpp_skip):
                failures.append(f"skip mismatch Q2-y={q2y} z-pT={zpt}: python={py_skip} table={cpp_skip}")
            py_start = Convert_All_Kinematic_Bins(f"Q2-y={q2y}, z-pT={zpt}", "MultiDim_Q2_y_z_pT_phi_h")
            cpp_start = conv_cpp(f"Q2-y={q2y}, z-pT={zpt}", "MultiDim_Q2_y_z_pT_phi_h")
            py_ok = py_start not in ["ERROR", "Error", None, ""]
            cpp_ok = cpp_start is not None
            if(py_ok != cpp_ok):
                failures.append(f"start presence mismatch Q2-y={q2y} z-pT={zpt}: python={py_start} cpp={cpp_start}")
            elif(py_ok and int(py_start) != int(cpp_start)):
                failures.append(f"start value mismatch Q2-y={q2y} z-pT={zpt}: python={py_start} cpp={cpp_start}")
            if(py_ok):
                slot = int(py_start)
                py_q = Convert_All_Kinematic_Bins(f"MultiDim_Q2_y_z_pT_phi_h={slot}", "Q2-y")
                py_z = Convert_All_Kinematic_Bins(f"MultiDim_Q2_y_z_pT_phi_h={slot}", "z-pT")
                cpp_q = conv_cpp(f"MultiDim_Q2_y_z_pT_phi_h={slot}", "Q2-y")
                cpp_z = conv_cpp(f"MultiDim_Q2_y_z_pT_phi_h={slot}", "z-pT")
                if(int(py_q) != int(cpp_q) or int(py_z) != int(cpp_z)):
                    failures.append(f"reverse mismatch slot={slot}: python=({py_q},{py_z}) cpp=({cpp_q},{cpp_z})")
                mid = slot + 1
                py_mid = Convert_All_Kinematic_Bins(f"MultiDim_Q2_y_z_pT_phi_h={mid}", "Q2-y")
                cpp_mid = conv_cpp(f"MultiDim_Q2_y_z_pT_phi_h={mid}", "Q2-y")
                py_mid_ok = py_mid not in ["ERROR", "Error", None, ""]
                cpp_mid_ok = cpp_mid is not None
                if(py_mid_ok != cpp_mid_ok):
                    failures.append(f"mid-slot presence mismatch slot={mid}: python={py_mid} cpp={cpp_mid}")
    return failures


def parse_args():
    p = argparse.ArgumentParser(description="Generate C++ dense-5D binning header for Dedicated_5D_Unfold.")
    p.add_argument("-o", "--output", default=DEFAULT_OUT, help="Output header path.\n")
    p.add_argument("--check", action="store_true", help="Compare generated tables to live Python maps.\n")
    return p.parse_args()


def main():
    args = parse_args()
    info = write_header(args.output)
    print(f"Wrote {info['out_path']}")
    print(f"  convert entries = {info['n_convert']}")
    print(f"  total hist bins = {info['total_hist_bins']}")
    failures = self_check(info)
    if(failures):
        print(f"SELF-CHECK FAILED ({len(failures)}):")
        for line in failures[:40]:
            print(f"  {line}")
        if(len(failures) > 40):
            print(f"  ... {len(failures) - 40} more")
        sys.exit(1)
    print("Self-check passed against live Python maps.")
    if(args.check):
        print("Check-only complete.")
    return 0


if(__name__ == "__main__"):
    sys.exit(main())
