#!/bin/bash

echo "Started at:"
date

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root -mod -all -nf -fi -sn "ZerothOrder" -t "Zero Order Acceptance Weights" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root -mod -all -nf -fi -sn 'ZerothOrder' -t 'Zero Order Acceptance Weights' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC'"

./Assign_Uncertainties_to_unfolding.py -si -c -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod -all -nf -fi -sn "FirstOrderAcc" -t "First Order Weights (with/without Acceptance Weights)" -ue -ln1 "Physics Modulations Only" -ln2 "Physics+Acceptance Weights" -r2 "New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025.root" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -c -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod -all -nf -fi -sn 'FirstOrderAcc' -t 'First Order Weights (with/without Acceptance Weights)' -ue -ln1 'Physics Modulations Only' -ln2 'Physics+Acceptance Weights' -r2 'New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025.root'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_FirstOrderAcc_Errors" -t "Errors from 1^{st} Order Weights" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -fr "New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_FirstOrderAcc_Errors' -t 'Errors from 1^{st} Order Weights' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC' -fr 'New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_ZerothOrder_Errors" -t "Errors from 0^{th} Order Weights" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -fr "New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root" -uej "Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_ZerothOrder_Errors' -t 'Errors from 0^{th} Order Weights' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC' -fr 'New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root' -uej 'Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_FirstOrderAcc_Errors" -t "Errors from 1^{st} Order Weights" -ue -fr "New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_FirstOrderAcc_Errors' -t 'Errors from 1^{st} Order Weights' -ue -fr 'New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_ZerothOrder_Errors" -t "Errors from 0^{th} Order Weights" -ue -fr "New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root" -uej "Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_ZerothOrder_Errors' -t 'Errors from 0^{th} Order Weights' -ue -fr 'New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root' -uej 'Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod_solo -all -fi -sn "FirstOrder_with_FirstOrderAcc_Errors" -t "First Order Modulations" -ue -ln1 "Physics Modulations Only" -fr "New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod_solo -all -fi -sn 'FirstOrder_with_FirstOrderAcc_Errors' -t 'First Order Modulations' -ue -ln1 'Physics Modulations Only' -fr 'New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn "FirstOrderAcc_with_FirstOrderAcc_Errors" -t "1st Order Modulations+Acceptance Weights" -ue -ln1 "Physics+Acceptance Weights" -fr "New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn 'FirstOrderAcc_with_FirstOrderAcc_Errors' -t '1st Order Modulations+Acceptance Weights' -ue -ln1 'Physics+Acceptance Weights' -fr 'New_Unfolded_Histos_From_FirstOrderAcc_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn "ZerothOrder_with_ZerothOrder_Errors" -t "0th Order Acceptance Weights and Errors" -ue -u "Bin" -ln1 "Corrected with Acceptance Weights Only" -fr "New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_Zero_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn 'ZerothOrder_with_ZerothOrder_Errors' -t '0th Order Acceptance Weights and Errors' -ue -u 'Bin' -ln1 'Corrected with Acceptance Weights Only' -fr 'New_Unfolded_Histos_From_ZerothOrder_as_of_12_2_2025_Copy_Zero_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_ZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "UnModified_Baseline" -t "Baseline with just normal unfolding" -ue -fr "Baseline_Unfolded_with_No_extra_uncertainties_added.root" -uej "Mod_Test_Unfolding_Bin_Differences_UnModified_Baseline_Test.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'UnModified_Baseline' -t 'Baseline with just normal unfolding' -ue -fr 'Baseline_Unfolded_with_No_extra_uncertainties_added.root' -uej 'Mod_Test_Unfolding_Bin_Differences_UnModified_Baseline_Test.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_AngleOnlyFirstOrderAcc_Errors" -t "Errors from 1^{st} Order Weights" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -fr "New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_AngleOnlyFirstOrderAcc_Errors' -t 'Errors from 1^{st} Order Weights' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC' -fr 'New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_AngleOnlyZerothOrder_Errors" -t "Errors from 0^{th} Order Weights" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -fr "New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyZerothOrder.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_AngleOnlyZerothOrder_Errors' -t 'Errors from 0^{th} Order Weights' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC' -fr 'New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_AngleOnlyFirstOrderAcc_Errors" -t "Errors from 1^{st} Order Weights" -ue -fr "New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_AngleOnlyFirstOrderAcc_Errors' -t 'Errors from 1^{st} Order Weights' -ue -fr 'New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn "Baseline_with_AngleOnlyZerothOrder_Errors" -t "Errors from 0^{th} Order Weights" -ue -fr "New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyZerothOrder.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -all -fi -sn 'Baseline_with_AngleOnlyZerothOrder_Errors' -t 'Errors from 0^{th} Order Weights' -ue -fr 'New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod_solo -all -fi -sn "FirstOrder_with_AngleOnlyFirstOrderAcc_Errors" -t "First Order Modulations" -ue -ln1 "Physics Modulations Only" -fr "New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy.root -mod_solo -all -fi -sn 'FirstOrder_with_AngleOnlyFirstOrderAcc_Errors' -t 'First Order Modulations' -ue -ln1 'Physics Modulations Only' -fr 'New_Unfolded_Histos_From_FirstOrder_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_AngleOnlyFirstOrderAcc_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn "AngleOnlyFirstOrderAcc_with_AngleOnlyFirstOrderAcc_Errors" -t "1st Order Modulations+Acceptance Weights" -ue -ln1 "Physics+Acceptance Weights (Angles Only)" -fr "New_Unfolded_Histos_From_AngleOnlyFirstOrderAcc_as_of_12_2_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_AngleOnlyFirstOrderAcc_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn 'AngleOnlyFirstOrderAcc_with_AngleOnlyFirstOrderAcc_Errors' -t '1st Order Modulations+Acceptance Weights' -ue -ln1 'Physics+Acceptance Weights (Angles Only)' -fr 'New_Unfolded_Histos_From_AngleOnlyFirstOrderAcc_as_of_12_2_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_AngleOnlyFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn "AngleOnlyZerothOrder_with_AngleOnlyZerothOrder_Errors" -t "Zero Order Acceptance Weights (Angles Only)" -ue -u "Bin" -ln1 "Corrected with Unweighted MC" -ln2 "Corrected with Weighted MC" -e -em "Ran in tmuxEvGen.\nBook-keeping message: Used this command to run this code:\n\t./Assign_Uncertainties_to_unfolding.py -si -r New_Unfolded_Histos_From_AngleOnlyZerothOrder_as_of_12_2_2025_Copy.root -mod_solo -ie -all -fi -sn 'AngleOnlyZerothOrder_with_AngleOnlyZerothOrder_Errors' -t 'Zero Order Acceptance Weights (Angles Only)' -ue -u 'Bin' -ln1 'Corrected with Unweighted MC' -ln2 'Corrected with Weighted MC'" 

echo "Done at:"
date

