#!/bin/bash

START_TIME="Started Running at:  $(date)"
echo "$START_TIME"


./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -data -all -nf -fi -sn "FixedZerothOrder" -t "Zero Order Acceptance Weights" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -data -all -nf -fi -sn 'FixedZerothOrder' -t 'Zero Order Acceptance Weights'"

./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -data -all -nf -fi -sn "FixedFirstOrder" -t "First Order Weights (without Acceptance Weights)" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -data -all -nf -fi -sn 'FixedFirstOrder' -t 'First Order Weights (without Acceptance Weights)'"

./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -data -all -nf -fi -sn "FixedFirstOrderAcc" -t "First Order Weights (with Acceptance Weights)" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -n -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -data -all -nf -fi -sn 'FixedFirstOrderAcc' -t 'First Order Weights (with Acceptance Weights)'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -u "mdf" -mod -all -nf -fi -sn "FixedZerothOrder" -t "Zero Order Acceptance Weights" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -u 'mdf' -mod -all -nf -fi -sn 'FixedZerothOrder' -t 'Zero Order Acceptance Weights'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -u "mdf" -mod -all -nf -fi -sn "FixedFirstOrder" -t "First Order Weights (without Acceptance Weights)" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -u 'mdf' -mod -all -nf -fi -sn 'FixedFirstOrder' -t 'First Order Weights (without Acceptance Weights)'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -u "mdf" -mod -all -nf -fi -sn "FixedFirstOrderAcc" -t "First Order Weights (with Acceptance Weights)" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -u 'mdf' -mod -all -nf -fi -sn 'FixedFirstOrderAcc' -t 'First Order Weights (with Acceptance Weights)'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -u "Acceptance" -mod -all -nf -fi -sn "FixedZerothOrder" -t "Zero Order Acceptance Weights" -ln1 "Unweighted MC" -ln2 "Weighted MC" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -u 'Acceptance' -mod -all -nf -fi -sn 'FixedZerothOrder' -t 'Zero Order Acceptance Weights' -ln1 'Unweighted MC' -ln2 'Weighted MC'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -u "Acceptance" -mod -all -nf -fi -sn "FixedFirstOrder" -t "First Order Weights (without Acceptance Weights)" -ln1 "Unweighted MC" -ln2 "Weighted MC" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -u 'Acceptance' -mod -all -nf -fi -sn 'FixedFirstOrder' -t 'First Order Weights (without Acceptance Weights)' -ln1 'Unweighted MC' -ln2 'Weighted MC'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -u "Acceptance" -mod -all -nf -fi -sn "FixedFirstOrderAcc" -t "First Order Weights (with Acceptance Weights)" -ln1 "Unweighted MC" -ln2 "Weighted MC" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -u 'Acceptance' -mod -all -nf -fi -sn 'FixedFirstOrderAcc' -t 'First Order Weights (with Acceptance Weights)' -ln1 'Unweighted MC' -ln2 'Weighted MC'"

./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -mj -mod -all -nf -fi -sn "FixedZerothOrder" -t "Zero Order Acceptance Weights" -ue -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -sf -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -mj -mod -all -nf -fi -sn 'FixedZerothOrder' -t 'Zero Order Acceptance Weights' -ue"

./Assign_Uncertainties_to_unfolding.py -si -c -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -mj -mod -all -nf -fi -sn "FixedFirstOrderAcc" -t "First Order Weights (with/without Acceptance Weights)" -ue -ln1 "Physics Modulations Only" -ln2 "Physics+Acceptance Weights" -r2 "New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -si -c -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -mj -mod -all -nf -fi -sn 'FixedFirstOrderAcc' -t 'First Order Weights (with/without Acceptance Weights)' -ue -ln1 'Physics Modulations Only' -ln2 'Physics+Acceptance Weights' -r2 'New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root'"

./Assign_Uncertainties_to_unfolding.py -all -fi -sn "Baseline_with_FixedFirstOrderAcc_Errors" -t "Errors from 1^{st} Order Weights" -ue -fr "New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -all -fi -sn 'Baseline_with_FixedFirstOrderAcc_Errors' -t 'Errors from 1^{st} Order Weights' -ue -fr 'New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -all -fi -sn "Baseline_with_FixedZerothOrder_Errors" -t "Errors from 0^{th} Order Weights" -ue -fr "New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root" -uej "Mod_Test_Unfolding_Bin_Differences_FixedZerothOrder.json" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -all -fi -sn 'Baseline_with_FixedZerothOrder_Errors' -t 'Errors from 0^{th} Order Weights' -ue -fr 'New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FixedZerothOrder.json'"

./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -mod_solo -all -fi -sn "FirstOrder_with_FixedFirstOrderAcc_Errors" -t "First Order Modulations" -ue -ln1 "Physics Modulations Only" -fr "New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025_Copy_First_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025.root -mod_solo -all -fi -sn 'FirstOrder_with_FixedFirstOrderAcc_Errors' -t 'First Order Modulations' -ue -ln1 'Physics Modulations Only' -fr 'New_Fixed_Unfolded_Histos_From_FirstOrder_as_of_12_11_2025_Copy_First_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -mod_solo -ie -all -fi -sn "FirstOrderAcc_with_FixedFirstOrderAcc_Errors" -t "1st Order Modulations+Acceptance Weights" -ue -ln1 "Physics+Acceptance Weights" -fr "New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root" -uej "Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root -mod_solo -ie -all -fi -sn 'FirstOrderAcc_with_FixedFirstOrderAcc_Errors' -t '1st Order Modulations+Acceptance Weights' -ue -ln1 'Physics+Acceptance Weights' -fr 'New_Fixed_Unfolded_Histos_From_FirstOrderAcc_as_of_12_11_2025.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FixedFirstOrderAcc.json'"

./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -mod_solo -ie -all -fi -sn "ZerothOrder_with_FixedZerothOrder_Errors" -t "0th Order Acceptance Weights and Errors" -ue -ln1 "Unfolded with Acceptance Weights Only" -fr "New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025_Copy_Zero_Order_Errors.root" -uej "Mod_Test_Unfolding_Bin_Differences_FixedZerothOrder.json" -e -em "Ran in tmuxEvGen.  \nBook-keeping message: Used this command to run this code:  \n\t ./Assign_Uncertainties_to_unfolding.py -r New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025.root -mod_solo -ie -all -fi -sn 'ZerothOrder_with_FixedZerothOrder_Errors' -t '0th Order Acceptance Weights and Errors' -ue -ln1 'Unfolded with Acceptance Weights Only' -fr 'New_Fixed_Unfolded_Histos_From_ZerothOrder_as_of_12_11_2025_Copy_Zero_Order_Errors.root' -uej 'Mod_Test_Unfolding_Bin_Differences_FixedZerothOrder.json'" 

echo "$START_TIME"
echo "Finished Running at: $(date)"

